### ISSUE TITLE
STEP1 관련 질문 드립니다.

### ISSUE THREAD

**Issue by torkks** [scalable-arch/URP2022F#3]
STEP1 관련 질문이 있어 올려드립니다.

1. 오늘 수업시간에 t_RCD를 IDLE-> ACTIVATING 천이 상황에서 시작한다고 언급하셨는데,
	 t_RCD는 ACTIVATING -> BANK_ACT 천이상황에서 카운팅이 시작되어야 하는 것이 아닌가 싶어 질문드립니다.
![image](https://user-images.githubusercontent.com/107017041/211475970-eb810de8-b308-4fe5-89f3-9b6f89717f73.png)

2. JEDEC pdf의 FSM 상태도를 살펴보면, WR 혹은 RD에서 PRE로 갈 수 있게끔 화살표가 있어 WR과 RD 상태에서도 PRE로 가도록 설계를 했는데, 오늘 수업시간에 예시로 들어주신 부분을 살펴보면 그 부분은 구현하시지 않고, BANK_ACT에서만 PRE로 갈 수 있게끔 하셨는데, 이에대한 이유를 알고싶습니다.

![image](https://user-images.githubusercontent.com/107017041/211476064-10ee2a9b-53ed-4aca-b00d-e959e5e3360a.png)

감사합니다!

**Comment by dale40** [comment]
안녕하세요,

1. ACTIVATING/BANK_ACTIVE state를 어떻게 정의하냐에 따라 다릅니다.

- BANK_ACTIVE state를 read와 write가 가능한 상태로 정의한다면, activation command가 나간 다음 tRCD가 지난 다음에 BANK_ACTIVE 상태에 진입해야 합니다. 그래서 이를 위해 중간에 ACTIVATING state를 두어서 BANK_ACTIVE 상태에서는 tRCD에 대한 체크 없이 read/write command를 issue할 수 있습니다.

- 반면에 BANK_ACTIVE state를 activation command가 issue된 상태로 정의한다면, activation command가 나간 다음에 바로 BANK_ACTIVE state로 전이할 수 있습니다 (ACTIVATING state필요 없음). 하지만 이 경우 BANK_ACTIVE state에서는 tRCD가 만족되었는 별개로 체크해야 합니다.

**Comment by dale40** [comment]
좋은 질문입니다.

Micron datasheet에서는 bank FSM이 READING/WRITING으로 바로 PRECHARGING으로 전이가 가능한 것으로 나와 있습니다. 하지만 우리 구현에서는 이러한 경우가 발생하지 않습니다.

READING/WRITING에서 바로 PRECHARGING으로 가기 위해서는 READING/WRITING의 마지막 cycle에 precharge command가 나가야 합니다.
하지만 주어진 timing parameter를 보면 READING/WRITING의 마지막 cycle에 precharge가 나가는 것이 불가능합니다.

먼저 READING의 마지막 cycle에 precharge가 나갈 수 있는지를 알아보겠습니다.
read-to-precharge의 최소 간격은 AL + BL/2 - 2CK + MAX(tRTP/tCK or 2CK)입니다 (Micron datasheet page 99). AL의 값과 tRTP의 값이 최소라고 하더라도 read-to-precharge의 최소 간격은 BL/2입니다. 이 경우, precharge가 나갈 수 있는 가장 빠른 cycle은 READING이 끝난 다음 cycle입니다.
비슷하게 Write의 경우에도 write-to-precharge의 최소 간격은 WL + BL/2 + tWR (Micron datasheet Figure 64)입니다. 따라서 Write가 완료된 뒤 시간이 좀 지나야 precharge를 보낼 수 있지 WRITING의 마지막 cycle에 precharge를 보낼 수 없습니다.

**Comment by torkks** [comment]
답변 감사합니다!
